--- #YAML:1.0
name:               Parse-NetApp-ASUP
version:            1.14
abstract:           Parse NetApp Weekly Auto Support Files
author:
    - Phil Pollard <bennie@cpan.org>
license:            artistic_2
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:               5.008001
    Test::Simple:       0
	File::Slurp:        9999.19
	Digest::MD5:        2.50
resources:
    bugtracker:
        web:  https://rt.cpan.org/Dist/Display.html?Name=Parse-NetApp-ASUP
    repository:
        type:  git
        url:   git://github.com/bennie/perl-Parse-NetApp-ASUP.git
        web:   http://github.com/bennie/perl-Parse-NetApp-ASUP
no_index:
    directory:
        - t
        - inc
provides:
    Parse::NetApp::ASUP:
        file: lib/Parse/NetApp/ASUP.pm
        version: 1.14
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
